### ISSUE TITLE
Some questions about  datasets

### ISSUE THREAD

**Issue by weiliuxm** [valeoai/DADA#3]
Hi, Vu.
Thank you for sharing the project.
I am confused about the setting of datasets, as presented in the README.md.
(1) There should have a subdirectory named Depth in the dataset directory data/SYNTHIA.  I have downloaded the file SYNTHIA_RAND_CVPR16.zip. However, I could not find a folder named Depth.
(2) There should have a subdirectory named val in the dataset directory data/Cityscapes/leftImg8bit. Only a folder name train is found in the data/Cityscapes/leftImg8bit.

Could you tell me how to generate the above two subfolder, please？
Thank you in advance.

**Comment by weiliuxm** [comment]
Problems have been resolved.

**Comment by yuheyuan** [comment]
> Problems have been resolved.

Hi， Do you remember how to solve the problem, because I meet the same problem
